import { Summary } from "@/types";
import { summaryToMarkdown } from "./summarizer";

/**
 * Generates a printable HTML document from a summary and opens the browser
 * print dialog, which allows saving as PDF.
 */
export function exportSummaryAsPDF(summary: Summary) {
  const md = summaryToMarkdown(summary);

  // Convert markdown to simple HTML
  let html = md
    .replace(/^# (.+)$/gm, '<h1 style="font-size:24px;font-weight:bold;margin-bottom:8px">$1</h1>')
    .replace(/^## (.+)$/gm, '<h2 style="font-size:18px;font-weight:bold;margin-top:24px;margin-bottom:12px;border-bottom:1px solid #e2e8f0;padding-bottom:8px">$1</h2>')
    .replace(/^### (.+)$/gm, '<h3 style="font-size:15px;font-weight:600;margin-top:16px;margin-bottom:8px">$1</h3>')
    .replace(/^\- (.+)$/gm, '<li style="margin-bottom:6px;margin-left:16px;line-height:1.6">$1</li>')
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/_(.+?)_/g, '<em style="color:#64748b">$1</em>')
    .replace(/\n\n/g, "<br/><br/>");

  // Wrap list items
  html = html.replace(
    /(<li[^>]*>.*?<\/li>\s*)+/g,
    (match) => `<ul style="list-style:disc;padding-left:24px">${match}</ul>`
  );

  const printWindow = window.open("", "_blank");
  if (!printWindow) return;

  printWindow.document.write(`<!DOCTYPE html>
<html>
<head>
  <title>${summary.title}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      max-width: 720px;
      margin: 0 auto;
      padding: 40px 32px;
      color: #1e293b;
      font-size: 14px;
      line-height: 1.7;
    }
    h1 { color: #0f172a; }
    h2 { color: #1e293b; }
    h3 { color: #334155; }
    strong { color: #0f172a; }
    @media print {
      body { padding: 20px; }
    }
  </style>
</head>
<body>
  ${html}
  <footer style="margin-top:40px;padding-top:16px;border-top:1px solid #e2e8f0;font-size:12px;color:#94a3b8">
    Generated by AcademicOS on ${new Date().toLocaleDateString()}
  </footer>
</body>
</html>`);
  printWindow.document.close();

  // Wait for content to render, then trigger print dialog
  setTimeout(() => {
    printWindow.print();
  }, 300);
}
